### ISSUE TITLE
Extension asking to install iCloud, but it's already installed

### ISSUE THREAD

**Issue by francescofact** [ArakawaHenri/iCloudPasswords_for_Firefox#1]
Hello, i tried installing it but the Firefox extension ask me to download iCloud for Windows, that is already downloaded and the Edge extension is working.
(I don't have chrome, just edge)

**Comment by ArakawaHenri** [comment]
Hi! I think you should download the tool for granting permissions [here](https://github.com/ArakawaHenri/Grant_Privileges_for_iCloudPasswords/releases/latest/download/grant_privileges.exe) and run it with administrator privilege as instructed.

**Comment by francescofact** [comment]
Already done it

**Comment by ArakawaHenri** [comment]
Is there any output from this program?

**Comment by francescofact** [comment]
Nope, it just returns

**Comment by ArakawaHenri** [comment]
Please ensure that you really ran this program since windows prevents programs downloaded from Internet from running as administrator. I’m pretty sure that the program would show the result in any cases.

**Comment by francescofact** [comment]
Yes, it has been runned ad Admina

**Comment by francescofact** [comment]
I found the problem. I you don't have the folder ".config" the script grant will not work

**Comment by ArakawaHenri** [comment]
Yes, I have found the problem and I am fixing the code.

**Comment by ArakawaHenri** [comment]
Sorry for the late reply. I've just had a few things to take care of.

**Comment by francescofact** [comment]
Also i found the extension super slow to load the password. Is that normal?

**Comment by ArakawaHenri** [comment]
This is strange, I also found when testing this Extension that it sometimes takes a long time to load the password, restarting the browser might help, I don't know if this is a problem with the iCloud client or Firefox.

**Comment by ArakawaHenri** [comment]
Just fixed the bug so I'm closing the issue. please let me know if you encounter any more problems with it. Thank you very much.

BTW, I just tested this on a freshly installed Windows PC and did not experience the password loading very slowly. I did encounter this in previous tests and hopefully I can find and fix the problem.
