### ISSUE TITLE
Extension does not work anymore?

### ISSUE THREAD

**Issue by InvitedToHell** [ArakawaHenri/iCloudPasswords_for_Firefox#2]
No idea why, but the extension stopped working for me several days ago. It cannot find the iCloud App as far as it seems, even tho it is open.

![image](https://user-images.githubusercontent.com/73737531/208902366-de983661-d56e-405a-9ab7-87fa6d31d630.png)
![image](https://user-images.githubusercontent.com/73737531/208902421-b384915d-3c3c-4ee6-ae96-1e68fcbe433a.png)

**Comment by ArakawaHenri** [comment]
I changed the Addon ID for some reason during the update, you can try reinstalling the 1.3.77.1 version in Releases (then uninstall the old one) and granting it permissions again.

**Comment by ArakawaHenri** [comment]
If you are still experiencing any problems, please let me know.

**Comment by ArakawaHenri** [comment]
(The program used to grant permissions has also been updated, and you need to download it again)

**Comment by InvitedToHell** [comment]
Thank you, I'll try that.

**Comment by InvitedToHell** [comment]
It works again! Thank you! Keep up the work c:
